version: "3"

services:

  app-saludo-env:
    build: ./app-saludo/src/
    ports:
      - "8081:8000"
    environment:
      ENG_MSG: 'Hello people!. I am a simple app and this is my route in english.\n'
    secrets:
      - SECRET_MSG

secrets:
  SECRET_MSG:
    file: mensaje_secreto.txt
