apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
  selector:
    appName: {{ .Values.app.name }}  # Potencia de helm: facilita trabajar con los campos "cruzados"
