version: '3.8'
services:
  api:
    build: .
    image: app-db-cargo
    container_name: app-server
    command: bash -c "cd app/database && alembic upgrade head && cd .. && fastapi run main.py --port 8080 --reload"
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .:/code
  db:
    image: postgres:alpine3.20
    container_name: app-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
    db: