apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appDB.name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.appDB.secrets.type }}
data:
{{- toYaml .Values.appDB.secrets.data | nindent 2 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appCargo.name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.appCargo.secrets.type }}
data:
{{- toYaml .Values.appCargo.secrets.data | nindent 2 }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appCargo.secrets.name }}-key
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.appCargo.secrets.dockerConfig }}
type: kubernetes.io/dockerconfigjson