---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appDB.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.appDB.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.appDB.service.port }}
      targetPort: {{ .Values.appDB.service.targetPort }}
  selector:
    {{- toYaml .Values.appDB.labels | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appCargo.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.appCargo.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.appCargo.service.port }}
      targetPort: {{ .Values.appCargo.service.targetPort }}
  selector:
    {{- toYaml .Values.appCargo.labels | nindent 4 }}