# Values por defecto
namespace: prod-k8s
app:
  name: app-saludo
  replicaCount: 1
  image: flor35677653/app-saludo:v1
  containerPort: 8000
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

service:
  type: ClusterIP
  port: 8081

secret:
  env:
    var: SECRETS_PATH
    path: "/run/secrets/app-saludo-secret/SECRET_MSG"
    msg: "a2FhIG5hYW1hIGZ0YWgnbiBjdGh1bGh1Cg=="

configMap:
  env:
    en_var: ENG_MSG
    en_key: english_message
  english_message: "Hello everyone!. I am a simple app and this is my route in english.\n"

volumes:
  name: secret-spell
  mount: "/run/secrets/app-saludo-secret"
  readOnly: true